services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h localhost -p 5432 -q -U ${POSTGRES_USERNAME}
      interval: 15s
      timeout: 15s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

volumes:
  postgres-data:
